# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   annotations:
#     kompose.cmd: kompose convert -f docker-compose.yml
#     kompose.version: 1.21.0 (992df58d8)
#   creationTimestamp: null
#   labels:
#     io.kompose.service: mongo
#   name: mongo
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       io.kompose.service: mongo
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       annotations:
#         kompose.cmd: kompose convert -f docker-compose.yml
#         kompose.version: 1.21.0 (992df58d8)
#       creationTimestamp: null
#       labels:
#         io.kompose.network/app-network: "true"
#         io.kompose.service: mongo
#     spec:
#       containers:
#       - image: mongo
#         imagePullPolicy: 
#         name: mongo
#         ports:
#         - containerPort: 27017
#         resources: {}
#         volumeMounts:
#         - mountPath: /data/db
#           name: data-volume
#       restartPolicy: Always
#       serviceAccountName: ""
#       volumes:
#       - name: data-volume
#         persistentVolumeClaim:
#           claimName: data-volume
# status: {}

apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: todo-mongodb
spec:
  volumes:
  - name: todo-mongo-vol
    persistentVolumeClaim:
      claimName: todo-pvc
  containers:
  - image: mongo
    name: container1
    command:
    - mongod
    - “ — bind_ip”
    - “0.0.0.0”
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: todo-mongo-vol
      mountPath: /data/db